### ISSUE TITLE
missing dependency jsck

### ISSUE THREAD

**Issue by gajjargaurav** [artilleryio/minigun-core#4]
@hassy the package.json is missing jsck dependency which you referenced at  https://github.com/artilleryio/minigun-core/blob/19b6556ed2ccde46b94c11f025a58f3436ef876c/lib/runner.js#L10

**Comment by hassy** [comment]
Fixed in https://github.com/artilleryio/minigun-core/commit/c122f21d8dd3e7630a6f31b5a3239e311376aba8
